version: '3.8'

services:
  api:
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 